db:
  dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
  dataSource:
    url: jdbc:postgresql://localhost:5432/distribuidas
    username: postgres
    password: admin
  hikari:
    minimumIdle: 5
    maximumPoolSize: 10
